name: Scrape Live Stream URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: "The URL to scrape for m3u8 links"
        required: true
        default: "https://news.abplive.com/live-tv"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Playwright
      run: |
        npm install playwright
        npx playwright install --with-deps chromium

    - name: Run Playwright script with dynamic URL
      env:
        TARGET_URL: ${{ github.event.inputs.url }}
      run: |
        echo -e "\033[1;36m🌀 Running Playwright Script... 🌀\033[0m"
        node scrape-script.js | tee playwright_output.txt

    - name: Display captured .m3u8 URLs
      run: |
        echo -e "\033[1;33m============================\033[0m"
        echo -e "\033[1;35m Scrape Results: \033[0m"
        echo -e "\033[1;33m============================\033[0m"
        cat playwright_output.txt
        echo -e "\033[1;33m============================\033[0m"
        grep 'Found .m3u8 URL:' playwright_output.txt || echo -e "\033[1;31mExit...\033[0m"
